-- 0009: Map visit tracking
ALTER TABLE locations ADD COLUMN IF NOT EXISTS visit_count INT NOT NULL DEFAULT 1;
ALTER TABLE locations ADD COLUMN IF NOT EXISTS last_visited_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP;
